version: 0.2
phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      - echo "Entered the pre-build phase"
      - $(aws ecr get-login  --no-include-email --region us-east-1)
  build:
    commands:
      - echo "Entered build phase"
      - cd Policy
      - mvn compile
      - mvn package
      - echo " building docker image"
      - docker build -t policy/policyapp .
      - docker tag policy/policyapp 038849744303.dkr.ecr.us-east-1.amazonaws.com/policy-registry:policyapp
  post_build:
    commands:
    - echo "Entered the post-build phase"
    - docker push 038849744303.dkr.ecr.us-east-1.amazonaws.com/policy-registry:policyapp
    - printf '[{"name":"policy-container","imageUri":"%s"}]' 038849744303.dkr.ecr.us-east-1.amazonaws.com/policy-registry:policyapp > taskdefinition.json
artifacts:
  files:
    - Policy/taskdefinition.json