version: 0.2
phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      - echo "Entered the pre-build phase"
      - $(aws ecr get-login  --no-include-email --region us-east-1)
  build:
    commands:
      - echo "Entered build phase"
      - cd Quotes
      - mvn compile
      - mvn package
      - echo " building docker image"
      - docker build -t quotes/quotesapp .
      - docker tag quotes/quotesapp 038849744303.dkr.ecr.us-east-1.amazonaws.com/quotes-registry:quotesapp
  post_build:
    commands:
    - echo "Entered the post-build phase"
    - docker push 038849744303.dkr.ecr.us-east-1.amazonaws.com/quotes-registry:quotesapp
    - printf '[{"name":"quotes-container","imageUri":"%s"}]' 038849744303.dkr.ecr.us-east-1.amazonaws.com/quotes-registry:quotesapp > taskdefinition.json
artifacts:
  files:
    - Quotes/taskdefinition.json